### ISSUE TITLE
Error: Cannot find module 'vue-eslint-parser' after doing npm install from v10.0.0

### ISSUE THREAD

**Issue by yamanoku** [vuejs/eslint-plugin-vue#2706]
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: 9.21.0** 
- **eslint-plugin-vue version: 10.0.0** 
- **Vue version: 3.5.13** 
- **Node version: 23.9.0** 
- **npm version: 10.9.2**
- **Operating System:   Ubuntu 24.04.2 LTS** 

**What did you expect to happen?**

Linting fine as in eslint-plugin-vue@10.0.0

**What actually happened?**

When updating eslint-plugin-vue to v10, an error occurred that the module vue-eslint-parser did not exist

https://github.com/yamanoku/vue_portfolio_template/actions/runs/13674391840/job/38231559625?pr=2339

<details>
<summary>CI Details</summary>

```
Oops! Something went wrong! :(

ESLint: 9.21.0

Error: Cannot find module 'vue-eslint-parser'
Require stack:
- /home/runner/work/vue_portfolio_template/vue_portfolio_template/node_modules/eslint-plugin-vue/lib/configs/base.js
- /home/runner/work/vue_portfolio_template/vue_portfolio_template/node_modules/eslint-plugin-vue/lib/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1405:15)
    at Function.resolve (node:internal/modules/helpers:145:19)
    at Object.<anonymous> (/home/runner/work/vue_portfolio_template/vue_portfolio_template/node_modules/eslint-plugin-vue/lib/configs/base.js:19:23)
    at Module._compile (node:internal/modules/cjs/loader:1734:14)
    at Object..js (node:internal/modules/cjs/loader:1899:[10](https://github.com/yamanoku/vue_portfolio_template/actions/runs/13674391840/job/38231559625?pr=2339#step:6:11))
    at Module.load (node:internal/modules/cjs/loader:1469:32)
    at Function._load (node:internal/modules/cjs/loader:[12](https://github.com/yamanoku/vue_portfolio_template/actions/runs/13674391840/job/38231559625?pr=2339#step:6:13)86:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:[14](https://github.com/yamanoku/vue_portfolio_template/actions/runs/13674391840/job/38231559625?pr=2339#step:6:15))
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1491:12)
Error: Process completed with exit code 2.
```

</details>

I saw that vue-eslint-parser moved to peerDependencies at https://github.com/vuejs/eslint-plugin-vue/pull/2670 Is this one related?

**Repository to reproduce this issue**

- https://github.com/yamanoku/vue_portfolio_template/
    -  `renovate/eslint-plugin-vue-10.x` branch
    - https://github.com/yamanoku/vue_portfolio_template/pull/2339
        - [vue-eslint-parser has been removed from package-lock.json](https://github.com/yamanoku/vue_portfolio_template/pull/2339/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519).

**Comment by yamanoku** [comment]
Sorry! I forgot I had set `legacy-peer-deps=true` in `.npmrc` in my repository. I'm closing this Issue 🙇🏼
